/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <gtest/gtest.h>

TEST(AppMainTest, Check1to1) {
    EXPECT_EQ(42, 42);
}

int main(int argc, char **argv) {
  ::testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
